---
title: "Hoffman's First Ride"

---


<div style="text-align: center; padding-top: 2em; font-size: 2.2em;, sans-serif;">

Strollology
</div>


<div style="text-align: center; font-size: 0.6em; color: #666; margin-top: 0.5em; margin-bottom: 1em;"> JOSHUA JAEGER | LOUIS OBERLI | LUKAS HUBER | ROMANO MADDALENA | FABIAN MUELLER </div>




<div style="text-align: center; padding-top: 0em; font-size: 1.2em;  font-family: 'sans-serif', sans-serif;">

</div>


<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/747188070&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-173105084" title="Brüders et al." target="_blank" style="color: #cccccc; text-decoration: none;">Brüders et al.</a> · <a href="https://soundcloud.com/user-173105084/sets/ergehungen" title="Ergehungen" target="_blank" style="color: #cccccc; text-decoration: none;">Ergehungen</a></div>


<div style="text-align: justify; padding-top: 0em; font-size: .8em;" line-height: 1.1;">

Strollology is contemplative cultural and aesthetic method to raise awareness of the conditions of perception of the environment and to expand environmental perception. It is based on experimental reflexive walks and aesthetic interventions. Together with my friends, we often go for expanded sound-walks, in which we share our recent musical discoveries. Each of us puts together a short music set with his/her most recent treasure discoveries. We all press play at the exactly same time (this usually takes a few attempts — but exacts synchronization is absolutely essential!), and then we walk and let the music guide our mind while enjoying the beauty of nature. 
</div>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css}
d-title {
    display: none;
  }
```


